#!/usr/bin/env python3
"""
Minimal GitHub API Wrapper for The Daily Amen AI
This script ONLY handles GitHub API calls - NO content generation logic.
All content is generated by the Agent Zero subagent.
"""

import os
import sys
import requests
import json
import base64
import re
from datetime import datetime

config_path = os.path.join(os.path.dirname(__file__), 'config.json')
with open(config_path, 'r') as f:
    config = json.load(f)

GITHUB_TOKEN = config.get('GITHUB_TOKEN', '')
REPO = config.get('REPO', 'hansen1015/hansen1015.github.io')

def get_github_headers():
    return {
        'Authorization': f'token {GITHUB_TOKEN}',
        'Accept': 'application/vnd.github.v3+json'
    }

def create_post(title, content, date=None):
    """Create a new blog post file in _posts/"""
    if date is None:
        from datetime import datetime, timedelta
    # Use Singapore Time (UTC+8)
    sgt_now = datetime.utcnow() + timedelta(hours=8)
    date = sgt_now.strftime('%Y-%m-%d')
    filename = f"{date}-{title.lower().replace(' ', '-')}.md"

    url = f'https://api.github.com/repos/{REPO}/contents/_posts/{filename}'

    # Check if file exists
    check = requests.get(url, headers=get_github_headers())
    sha = None
    if check.status_code == 200:
        sha = check.json().get('sha')

    data = {
        'message': f'AI-generated daily reflection: {title}',
        'content': base64.b64encode(content.encode('utf-8')).decode('utf-8'),
        'branch': 'master'
    }
    if sha:
        data['sha'] = sha

    response = requests.put(url, headers=get_github_headers(), json=data)
    return response.status_code == 201 or response.status_code == 200

def post_comment(discussion_id, body):
    """Post a comment to a GitHub Discussion"""
    url = f'https://api.github.com/repos/{REPO}/discussions/{discussion_id}/comments'
    data = {'body': body}
    response = requests.post(url, headers=get_github_headers(), json=data)
    return response.status_code == 201

def post_issue_comment(issue_number, body):
    """Post a comment to a GitHub Issue"""
    url = f'https://api.github.com/repos/{REPO}/issues/{issue_number}/comments'
    data = {'body': body}
    response = requests.post(url, headers=get_github_headers(), json=data)
    return response.status_code == 201

def fetch_discussions(limit=15):
    """Fetch recent GitHub Discussions"""
    url = f'https://api.github.com/repos/{REPO}/discussions'
    params = {'per_page': limit}
    response = requests.get(url, headers=get_github_headers(), params=params)
    return response.json() if response.status_code == 200 else []

def fetch_comments(discussion_id):
    """Fetch comments from a discussion"""
    url = f'https://api.github.com/repos/{REPO}/discussions/{discussion_id}/comments'
    response = requests.get(url, headers=get_github_headers())
    return response.json() if response.status_code == 200 else []

def fetch_issues(limit=20):
    """Fetch open GitHub Issues"""
    url = f'https://api.github.com/repos/{REPO}/issues'
    params = {'state': 'open', 'per_page': limit}
    response = requests.get(url, headers=get_github_headers(), params=params)
    return response.json() if response.status_code == 200 else []

def fetch_issue_comments(issue_number):
    """Fetch comments from an issue"""
    url = f'https://api.github.com/repos/{REPO}/issues/{issue_number}/comments'
    response = requests.get(url, headers=get_github_headers())
    return response.json() if response.status_code == 200 else []

def add_label(issue_number, label_name):
    """Add a label to an issue"""
    url = f'https://api.github.com/repos/{REPO}/issues/{issue_number}/labels'
    data = [label_name]
    response = requests.post(url, headers=get_github_headers(), json=data)
    return response.status_code == 201

def publish_post_from_file(filepath):
    """Read a markdown file and publish it to GitHub via API"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract title from frontmatter
    title_match = re.search(r"title:\\s*[\"']?([^\"'\\n]+)", content)
    title = title_match.group(1).strip() if title_match else 'Daily Reflection'

    # Get filename
    filename = os.path.basename(filepath)

    # Upload to GitHub
    url = f'https://api.github.com/repos/{REPO}/contents/_posts/{filename}'

    # Check if file exists
    check = requests.get(url, headers=get_github_headers())
    sha = None
    if check.status_code == 200:
        sha = check.json().get('sha')

    data = {
        'message': f'AI-generated daily reflection: {title}',
        'content': base64.b64encode(content.encode('utf-8')).decode('utf-8'),
        'branch': 'master'
    }
    if sha:
        data['sha'] = sha

    response = requests.put(url, headers=get_github_headers(), json=data)

    if response.status_code in [200, 201]:
        print(f"Published: {filename}")
        print(f"   Title: {title}")
        return True
    else:
        print(f"Failed: {response.status_code}")
        print(f"   {response.text}")
        return False

def publish_all_posts_in_folder(folder_path):
    """Publish all .md files in a folder to GitHub"""
    published = 0
    failed = 0

    for filename in os.listdir(folder_path):
        if filename.endswith('.md'):
            filepath = os.path.join(folder_path, filename)
            if publish_post_from_file(filepath):
                published += 1
            else:
                failed += 1

    print(f"Summary: {published} published, {failed} failed")
    return published > 0

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python github_api.py publish <filepath>     - Publish single post")
        print("  python github_api.py publish_folder <path>  - Publish all posts in folder")
        print("  python github_api.py test                   - Test connection")
        sys.exit(1)

    command = sys.argv[1]

    if command == 'publish' and len(sys.argv) >= 3:
        publish_post_from_file(sys.argv[2])
    elif command == 'publish_folder' and len(sys.argv) >= 3:
        publish_all_posts_in_folder(sys.argv[2])
    elif command == 'test':
        url = f'https://api.github.com/repos/{REPO}'
        response = requests.get(url, headers=get_github_headers())
        if response.status_code == 200:
            print("GitHub API connection successful")
            print(f"   Repo: {REPO}")
        else:
            print(f"GitHub API connection failed: {response.status_code}")
    else:
        print(f"Unknown command: {command}")
        sys.exit(1)
