#!/usr/bin/env python3
"""
Minimal GitHub API Wrapper for The Daily Amen AI
This script ONLY handles GitHub API calls - NO content generation logic.
All content is generated by the Agent Zero subagent.
"""

import os
import sys
import requests
import json
from datetime import datetime

config_path = os.path.join(os.path.dirname(__file__), 'config.json')
with open(config_path, 'r') as f:
    config = json.load(f)

GITHUB_TOKEN = config.get('GITHUB_TOKEN', '')
REPO = config.get('REPO', 'hansen1015/hansen1015.github.io')

def get_github_headers():
    return {
        'Authorization': f'token {GITHUB_TOKEN}',
        'Accept': 'application/vnd.github.v3+json'
    }

def create_post(title, content, date=None):
    """Create a new blog post file in _posts/"""
    if date is None:
        date = datetime.now().strftime('%Y-%m-%d')
    filename = f"{date}-{title.lower().replace(' ', '-')}.md"

    url = f'https://api.github.com/repos/{REPO}/contents/_posts/{filename}'

    # Check if file exists
    check = requests.get(url, headers=get_github_headers())
    sha = None
    if check.status_code == 200:
        sha = check.json().get('sha')

    data = {
        'message': f'AI-generated daily reflection: {title}',
        'content': requests.utils.to_native_string(content.encode('base64')) if hasattr(content, 'encode') else content,
        'branch': 'master'
    }
    if sha:
        data['sha'] = sha

    response = requests.put(url, headers=get_github_headers(), json=data)
    return response.status_code == 201 or response.status_code == 200

def post_comment(discussion_id, body):
    """Post a comment to a GitHub Discussion"""
    url = f'https://api.github.com/repos/{REPO}/discussions/{discussion_id}/comments'
    data = {'body': body}
    response = requests.post(url, headers=get_github_headers(), json=data)
    return response.status_code == 201

def post_issue_comment(issue_number, body):
    """Post a comment to a GitHub Issue"""
    url = f'https://api.github.com/repos/{REPO}/issues/{issue_number}/comments'
    data = {'body': body}
    response = requests.post(url, headers=get_github_headers(), json=data)
    return response.status_code == 201

def fetch_discussions(limit=15):
    """Fetch recent GitHub Discussions"""
    url = f'https://api.github.com/repos/{REPO}/discussions'
    params = {'per_page': limit}
    response = requests.get(url, headers=get_github_headers(), params=params)
    return response.json() if response.status_code == 200 else []

def fetch_comments(discussion_id):
    """Fetch comments from a discussion"""
    url = f'https://api.github.com/repos/{REPO}/discussions/{discussion_id}/comments'
    response = requests.get(url, headers=get_github_headers())
    return response.json() if response.status_code == 200 else []

def fetch_issues(limit=20):
    """Fetch open GitHub Issues"""
    url = f'https://api.github.com/repos/{REPO}/issues'
    params = {'state': 'open', 'per_page': limit}
    response = requests.get(url, headers=get_github_headers(), params=params)
    return response.json() if response.status_code == 200 else []

def fetch_issue_comments(issue_number):
    """Fetch comments from an issue"""
    url = f'https://api.github.com/repos/{REPO}/issues/{issue_number}/comments'
    response = requests.get(url, headers=get_github_headers())
    return response.json() if response.status_code == 200 else []

def add_label(issue_number, label_name):
    """Add a label to an issue"""
    url = f'https://api.github.com/repos/{REPO}/issues/{issue_number}/labels'
    data = [label_name]
    response = requests.post(url, headers=get_github_headers(), json=data)
    return response.status_code == 201

if __name__ == '__main__':
    print("GitHub API Wrapper - Use as module, not standalone")
